included:
  - Chumi

excluded:
  - Pods
  - Chumi/Extensions/PickerExtensions

line_length:
    warning: 300
    error: 400
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

disabled_rules:
  - force_cast
  - identifier_name

